# Generated by Django 4.0.6 on 2022-07-30 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0002_genre_book_series_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter book title', max_length=255, verbose_name='Book title')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Enter price in BYN', max_digits=7, null=True, verbose_name='Book price')),
                ('publ_year', models.DateField(blank=True, help_text='Enter publication year', null=True, verbose_name='Year of publication')),
                ('pages', models.SmallIntegerField(blank=True, default=1, help_text='Enter amount pages', null=True, verbose_name='Pages')),
                ('weight', models.IntegerField(blank=True, help_text='Enter weight in g', null=True, verbose_name='Weight')),
                ('available_books', models.SmallIntegerField(blank=True, default=1, help_text='Enter amount available books', null=True, verbose_name='Amount available books')),
                ('is_available', models.BooleanField(blank=True, default=False, null=True, verbose_name='Available for order')),
                ('create_date', models.DateTimeField(editable=False, help_text="Date of create book's card", verbose_name='Date add card')),
                ('update_date', models.DateTimeField(help_text='Enter publication year', verbose_name='Date add book')),
                ('book_cover', models.CharField(choices=[('cardboard', 'Cardboard'), ('hardback', 'Hardback'), ('hidebound', 'Hidebound'), ('soft', 'Soft')], default='soft', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_book', to='reference.author')),
            ],
            options={
                'ordering': ('-title',),
            },
        ),
    ]
