# Generated by Django 4.0.6 on 2022-08-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookcard_genre_bookcard_publ_hous_bookcard_series_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcard',
            old_name='create_date',
            new_name='Date of create book card',
        ),
    ]
