# Generated by Django 4.0.6 on 2022-08-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_genre_book_series_book'),
        ('book', '0003_rename_create_date_bookcard_date of create book card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcard',
            options={'ordering': ['-title']},
        ),
        migrations.AddField(
            model_name='bookcard',
            name='age_restrictions',
            field=models.CharField(choices=[('1', '0+'), ('2', '6+'), ('3', '12+'), ('4', '16+'), ('5', '18+')], default='1', max_length=5, verbose_name='Age restrictions of book'),
        ),
        migrations.AddField(
            model_name='bookcard',
            name='format',
            field=models.CharField(choices=[('1', 'Foolscap octavo'), ('2', 'Crown octavo'), ('3', 'Demy octavo'), ('4', 'Royal octavo ')], default='1', max_length=5, verbose_name='Book format'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='book_cover',
            field=models.CharField(choices=[('1', 'Cardboard'), ('2', 'Hardback'), ('3', 'Hidebound'), ('4', 'Soft')], default='4', max_length=10, verbose_name='Book cover'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='genre',
            field=models.ManyToManyField(related_name='genre_book', to='reference.genre_book'),
        ),
    ]
