# Generated by Django 4.0.6 on 2022-08-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_genre_book_series_book'),
        ('book', '0004_alter_bookcard_options_bookcard_age_restrictions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcard',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Pictire of book'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='Date of create book card',
            field=models.DateTimeField(auto_now_add=True, help_text="Date of create book's card", verbose_name='Date add card'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='age_restrictions',
            field=models.CharField(blank=True, choices=[('1', '0+'), ('2', '6+'), ('3', '12+'), ('4', '16+'), ('5', '18+')], default='1', max_length=5, null=True, verbose_name='Age restrictions of book'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='book_cover',
            field=models.CharField(blank=True, choices=[('1', 'Cardboard'), ('2', 'Hardback'), ('3', 'Hidebound'), ('4', 'Soft')], default='4', max_length=10, null=True, verbose_name='Book cover'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='format',
            field=models.CharField(blank=True, choices=[('1', 'Foolscap octavo'), ('2', 'Crown octavo'), ('3', 'Demy octavo'), ('4', 'Royal octavo ')], default='1', max_length=5, null=True, verbose_name='Book format'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='genre_book', to='reference.genre_book'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='publ_hous',
            field=models.ManyToManyField(blank=True, null=True, related_name='publ_house_book', to='reference.publishinghous'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='series',
            field=models.ManyToManyField(blank=True, null=True, related_name='seres_book', to='reference.series_book'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='Enter publication year', verbose_name='Date add book'),
        ),
    ]
