# Generated by Django 4.0.6 on 2022-08-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_alter_author_second_name'),
        ('book', '0005_bookcard_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcard',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='genre_book', to='reference.genre_book'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, help_text='Enter price in BYN', max_digits=7, null=True, verbose_name='Book price'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='publ_hous',
            field=models.ManyToManyField(blank=True, related_name='publ_house_book', to='reference.publishinghous'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='seres_book', to='reference.series_book'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='weight',
            field=models.IntegerField(blank=True, default=1, help_text='Enter weight in g', null=True, verbose_name='Weight'),
        ),
    ]
