# Generated by Django 4.0.6 on 2022-08-09 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_alter_author_second_name'),
        ('book', '0006_alter_bookcard_genre_alter_bookcard_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcard',
            name='genre',
        ),
        migrations.AddField(
            model_name='bookcard',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genre_book', to='reference.genre_book'),
        ),
        migrations.RemoveField(
            model_name='bookcard',
            name='publ_hous',
        ),
        migrations.AddField(
            model_name='bookcard',
            name='publ_hous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publ_house_book', to='reference.publishinghous'),
        ),
        migrations.RemoveField(
            model_name='bookcard',
            name='series',
        ),
        migrations.AddField(
            model_name='bookcard',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seres_book', to='reference.series_book'),
        ),
    ]
