# Generated by Django 4.0.6 on 2022-08-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_alter_author_second_name'),
        ('book', '0008_remove_bookcard_genre_bookcard_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcard',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='genre_book', to='reference.genre_book'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='seres_book', to='reference.series_book'),
        ),
    ]
