# Generated by Django 4.0.6 on 2022-08-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_bookcard_genre_alter_bookcard_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcard',
            name='age_restrictions',
            field=models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], default='0+', max_length=5, null=True, verbose_name='Age restrictions of book'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='book_cover',
            field=models.CharField(blank=True, choices=[('Cardboard', 'Cardboard'), ('Hardback', 'Hardback'), ('Hidebound', 'Hidebound'), ('Soft', 'Soft')], default='Soft', max_length=10, null=True, verbose_name='Book cover'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='format',
            field=models.CharField(blank=True, choices=[('Foolscap octavo', 'Foolscap octavo'), ('Crown octavo', 'Crown octavo'), ('Demy octavo', 'Demy octavo'), ('Royal octavo', 'Royal octavo')], default='Royal octavo', max_length=20, null=True, verbose_name='Book format'),
        ),
    ]
