# Generated by Django 4.0.6 on 2022-08-04 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0004_alter_bookcard_options_bookcard_age_restrictions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, help_text='Date first create of Cart', null=True)),
                ('update_date', models.DateField(auto_now=True, help_text='Date update of Cart', null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
        ),
        migrations.CreateModel(
            name='BookInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='quantity books in cart')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Sum price')),
                ('create_date', models.DateField(auto_now_add=True, help_text='Date first add book in Cart', null=True)),
                ('update_date', models.DateField(auto_now=True, help_text='Date last update of book in Cart', null=True)),
                ('book', models.ForeignKey(help_text='Book in Cart', on_delete=django.db.models.deletion.PROTECT, to='book.bookcard', verbose_name='Book')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.cart', verbose_name='customer')),
            ],
        ),
    ]
