# Generated by Django 4.0.6 on 2022-08-05 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_bookcard_options_bookcard_age_restrictions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='book',
            field=models.ForeignKey(help_text='Book in Cart', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='book.bookcard', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='bookincart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='order.cart', verbose_name='Books in Cart'),
        ),
        migrations.AlterField(
            model_name='bookincart',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Sum price'),
        ),
        migrations.AlterField(
            model_name='bookincart',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantity books in cart'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='customer'),
        ),
    ]
