# Generated by Django 4.0.6 on 2022-08-09 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0006_alter_bookcard_genre_alter_bookcard_price_and_more'),
        ('order', '0002_alter_bookincart_book_alter_bookincart_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='book',
            field=models.ForeignKey(help_text='Book in Cart', on_delete=django.db.models.deletion.PROTECT, related_name='books_in', to='book.bookcard', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='bookincart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_in', to='order.cart', verbose_name='Books in Cart'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create_date',
            field=models.DateField(auto_now_add=True, help_text='Date first create of Cart', null=True, verbose_name='Created order date'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usercarts', to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='update_date',
            field=models.DateField(auto_now=True, help_text='Date update of Cart', null=True, verbose_name='Updated order date'),
        ),
    ]
