# Generated by Django 4.0.6 on 2022-08-15 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cart_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_in', to='order.cart', verbose_name='Cart'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, help_text='Date first add book in Cart', null=True)),
                ('update_date', models.DateField(auto_now=True, help_text='Date last update of book in Cart', null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.cart', verbose_name='Cart')),
            ],
        ),
    ]
