# Generated by Django 4.0.6 on 2022-08-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderstatus_alter_order_options_order_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-create_date',), 'verbose_name': 'cart', 'verbose_name_plural': 'carts'},
        ),
    ]
