# Generated by Django 4.0.6 on 2022-08-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_cart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookincart',
            options={'ordering': ('-create_date',), 'verbose_name_plural': 'Books'},
        ),
    ]
