# Generated by Django 4.0.6 on 2022-07-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter author name', max_length=25, verbose_name="Author's name")),
                ('second_name', models.CharField(blank=True, help_text='Enter author name', max_length=25, null=True)),
                ('surname', models.CharField(help_text='Enter author surname', max_length=25, verbose_name="Author's surname")),
                ('date_birth', models.DateField(blank=True, help_text="Enter author's birth year", null=True)),
                ('date_death', models.DateField(blank=True, help_text="Enter author's year of death", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublishingHous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Publishing Hous's name")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
    ]
